site_name: Famintos Burguer   

repo_name: "Famintos GitHub"
repo_url: https://github.com/mdsreq-fga-unb/2024.2-T01-FamintosBurguer/tree/main

nav:
  - Home Page: index.md
  - Projeto: projeto.md
  - Documentação de Requisitos:
    - 📂 Documentação: ProdutoProjeto/Documentacao.md
    - 1. Videos Apresentação:
      - ProdutoProjeto/1. Videos Apresentação/1_video.md
      - ProdutoProjeto/1. Videos Apresentação/2_video.md
      - ProdutoProjeto/1. Videos Apresentação/3_video.md
      - ProdutoProjeto/1. Videos Apresentação/4_video.md
    - 2. Visao Produto Projeto:
        - 1. Cenário Atual Do Cliente e Do Negócio: ProdutoProjeto/2. Visao Produto Projeto/1_Cenário.md
        - 2. Solução Proposta: ProdutoProjeto/2. Visao Produto Projeto/2_Solucao.md
        - 3. Estratégias De Engenharia De Software: ProdutoProjeto/2. Visao Produto Projeto/3_Estrategia.md
        - 4. Cronograma e Entregas: ProdutoProjeto/2. Visao Produto Projeto/4_Cronograma.md
        - 5. Interação Entre Equipe e Cliente: ProdutoProjeto/2. Visao Produto Projeto/5_Interação.md
        - 6. Engenharia de Requisitos: ProdutoProjeto/2. Visao Produto Projeto/6_ERequisitos.md
        - 7. DoR e DoD:
          - ProdutoProjeto/2. Visao Produto Projeto/7. DoR e DoD/DoR.md
          - ProdutoProjeto/2. Visao Produto Projeto/7. DoR e DoD/DoD.md
        - 8. Backlog Projeto:
          - ProdutoProjeto/2. Visao Produto Projeto/8. Backlog Projeto/1_Requisitos.md
          - ProdutoProjeto/2. Visao Produto Projeto/8. Backlog Projeto/2_Temas.md
          - ProdutoProjeto/2. Visao Produto Projeto/8. Backlog Projeto/3_Epicos.md
          - ProdutoProjeto/2. Visao Produto Projeto/8. Backlog Projeto/4_User Stories.md
          - ProdutoProjeto/2. Visao Produto Projeto/8. Backlog Projeto/5_Backlog.md
          - ProdutoProjeto/2. Visao Produto Projeto/8. Backlog Projeto/6_MVP.md
        - 9. Referências Bibliográficas: ProdutoProjeto/2. Visao Produto Projeto/9_Referências.md
    - 3. Protótipo de Produto: ProdutoProjeto/Prototipo.md
    - 4. Estudos de caso:    
        - Product Backlog Building: 'ProdutoProjeto/Estudo de caso/PBB.md'
        - User Story Mapping: 'ProdutoProjeto/Estudo de caso/USM.md'
        - Diagrama de Casos de Uso: 'ProdutoProjeto/Estudo de caso/DCU.md'
        - Especificações Casos de Uso:
          - ProdutoProjeto/Estudo de caso/ECU/AgendarConsulta.md
          - ProdutoProjeto/Estudo de caso/ECU/BuscarServicoSaude.md
          - ProdutoProjeto/Estudo de caso/ECU/AvaliarAtendimento.md
          - ProdutoProjeto/Estudo de caso/ECU/AtualizarProntuario.md
    - 5. Lições Aprendidas: ProdutoProjeto/Lições.md
  - Atas Reuniões: Atas


markdown_extensions:
  - tables
  - md_in_html  
  - toc:
      title: Tópicos
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme: 
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: docs/overrides
  language: pt-BR
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

  palette:
      - scheme: default
        primary: yellow
        accent: amber
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode

      - scheme: slate
        primary: indigo
        accent: light-blue
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    
  logo: img/hamburguer.png
  favicon: img/hamburguer_icon.png
  highlightjs: true

plugins:
  - search
  - include_dir_to_nav
  - glightbox

extra_css:
  - stylesheets/extra.css