site_name: Famintos Burguer   

nav:
  - Projeto e Documentação: index.md
  - Visão Do Produto E Projeto: ProdutoProjeto

markdown_extensions:
  - tables
  - md_in_html  
  - toc:
      title: Tópicos
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

theme: 
  name: material
  palette:
      - scheme: default
        primary: yellow
        accent: amber
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

    # Palette toggle for dark mode
      - scheme: slate
        primary: indigo
        accent: light-blue
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    
  logo: img/hamburguer.png
  favicon: img/hamburguer_icon.png
  highlightjs: true

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - include_dir_to_nav
