site_name: Famintos Burguer   

repo_name: "Famintos GitHub"
repo_url: https://github.com/mdsreq-fga-unb/2024.2-T01-FamintosBurguer/tree/main

nav:
  - Home Page: index.md
  - Projeto: projeto.md
  - Visão Do Produto E Projeto: ProdutoProjeto
  - Atas Reuniões: Atas

markdown_extensions:
  - tables
  - md_in_html  
  - toc:
      title: Tópicos
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme: 
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: docs/overrides
  language: pt-BR
  palette:
      - scheme: default
        primary: yellow
        accent: amber
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode

      - scheme: slate
        primary: indigo
        accent: light-blue
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    
  logo: img/hamburguer.png
  favicon: img/hamburguer_icon.png
  highlightjs: true

plugins:
  - search
  - include_dir_to_nav
  - glightbox

extra_css:
  - stylesheets/extra.css